name: 'Dispatched Azure Linux VM (based upon toolset image)'

on:
  workflow_dispatch:
    inputs:
      resourceGroupName:
        description: 'The name of an existing resource group'
        required: true
      vmName:
        description: 'The name given to bastion VM that provides a curated toolset'
        required: true
      suffix:
        description: 'A Virtual Network suffix.  Used for looking up the subnet where this bastion will be running and creating a network interface and public IP.'
        required: true
      action:
        required: true
        type: choice
        description: Create (new) or destroy (existing)
        options:
        - create
        - destroy

jobs:
  create-bastion:
    uses: ./.github/workflows/azure-bastion.yml
    with:
      vmName: ${{ github.event.inputs.vmName }}
      suffix: ${{ github.event.inputs.suffix }}
      resourceGroupName: ${{ github.event.inputs.resourceGroupName }}
      action: ${{ github.event.inputs.action }}
    secrets:
      AZURE_AD_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      AZURE_AD_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_AD_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      AZURE_REGION: ${{ secrets.AZURE_REGION }}
      TF_BACKEND_resource_group_name: ${{ secrets.TF_BACKEND_resource_group_name }}
      TF_BACKEND_storage_account_name: ${{ secrets.TF_BACKEND_storage_account_name }}
      TF_BACKEND_storage_container_name:  ${{ secrets.TF_BACKEND_storage_container_name }}