name: 'Dipatched Add Secrets to a KeyVault'


on:
  workflow_dispatch:
    inputs:
      resourceGroupName:
        description: 'The name of the resource group to create the kv in'
        required: true
      vaultName:
        description: 'The name of the key vault'
        required: true
      secretMap:
        description: 'A string format of the keys/secrets to add to the vault'
        required: true
        default: '{"example":"secret","secret2":"secret"}'
      stateName:
        description: 'A unique string name to use for tfstate (e.g., acr)'
        required: true
      action:
        required: true
        type: choice
        description: Create (new) or destroy (existing)
        options:
        - create
        - destroy

jobs:
  update-kv-secrets:
    uses: ./.github/workflows/azure-keyvault-secrets.yml
    with:
      resourceGroupName: ${{ github.event.inputs.resourceGroupName }}
      vaultName: ${{ github.event.inputs.vaultName }}
      stateName: ${{ github.event.inputs.stateName }}
      action: ${{ github.event.inputs.action }}
    secrets:
      secretMap: ${{ github.event.inputs.secretMap }}
      AZURE_AD_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      AZURE_AD_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_AD_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      AZURE_REGION: ${{ secrets.AZURE_REGION }}
      TF_BACKEND_resource_group_name: ${{ secrets.TF_BACKEND_resource_group_name }}
      TF_BACKEND_storage_account_name: ${{ secrets.TF_BACKEND_storage_account_name }}
      TF_BACKEND_storage_container_name:  ${{ secrets.TF_BACKEND_storage_container_name }}